# Generated by Django 3.0.5 on 2020-06-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200606_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='genre',
            new_name='food_type',
        ),
    ]
